config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # C
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  # R
  get 'tasks', to: 'tasks#index'
  # R just 1
  get 'tasks/:id', to: 'tasks#show', as: :task

  # U
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update'

  # D
  delete 'tasks/:id', to: 'tasks#destroy'

  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :set_tasks
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://use.fontawesome.com/releases/v5.8.1/css/all.css" %>

    <%= stylesheet_link_tag  "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<h1 class='text-center'>Create new task</h1>

<%= form_for(@task) do |f| %>
<div class="box">

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area :details, size: "60x12", class: 'form-control' %>
  </div>
  <div class="form-group">

    <%= f.check_box :completed %>
    <%= f.label :completed %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
</div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="box">
  <h1>My Tasks</h1>

  <% @tasks.each do |task| %>
    <p><% if task.completed %>
      <i class="far fa-check-square"></i>
    <% else %>
      <span class="greyed"><i class="far fa-check-square"></i></span>
    <% end %>
      <strong><%= link_to task.title, task_path(task) %></strong> - Completed: <%= task.completed %>
      <%= link_to 'Delete', task_path(task), method: :delete, data: { confirm: "Do you really want to delete '#{task.title}'?"} %></p>

  <% end %>

  <%= link_to "Create new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="box">
  <h2><%= @task.title %></h2>
  <p><%= @task.details %></p>
  <p>
    <% if @task.completed %>
      <i class="far fa-check-square"></i> This task is completed
    <% else %>
      <span class="greyed"><i class="far fa-check-square"></i></span> This task is not completed
    <% end %>
  </p>
  <p><%= link_to 'Edit this task', task_edit_path %></p>
  <p><%= link_to 'Back to tasks', tasks_path %></p>
</div>